### ISSUE TITLE
JSONDecodeError during Bootstrap

### ISSUE THREAD

**Issue by beatreichenbach** [ynput/ayon-backend#95]
Hello,

I'm getting this error when running the bootstrap on a brand new server just cloned and started on docker after running `make setup`:
```
2024-02-22 18:24:58 GOOD NEWS  server          Server is now ready to connect
2024-02-22T23:26:20.951748500Z 2024-02-22 18:26:20 ERROR      admin           [GET] /onboarding/releases/2024.01.0-full: UNHANDLED EXCEPTION
2024-02-22T23:26:20.951807735Z 2024-02-22 18:26:20 ERROR      server          Expecting value: line 1 column 1 (char 0)
2024-02-22T23:26:20.956059752Z [2024-02-22 18:26:20 -0500] [37] [ERROR] Exception in ASGI application
2024-02-22T23:26:20.956077572Z Traceback (most recent call last):
2024-02-22T23:26:20.956082611Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-02-22T23:26:20.956086848Z     result = await app(  # type: ignore[func-returns-value]
2024-02-22T23:26:20.956105789Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956110383Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-02-22T23:26:20.956114343Z     return await self.app(scope, receive, send)
2024-02-22T23:26:20.956117995Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956136794Z   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-02-22T23:26:20.956141567Z     await super().__call__(scope, receive, send)
2024-02-22T23:26:20.956145182Z   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024-02-22T23:26:20.956149215Z     await self.middleware_stack(scope, receive, send)
2024-02-22T23:26:20.956152891Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-02-22T23:26:20.956156688Z     raise exc
2024-02-22T23:26:20.956160019Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-02-22T23:26:20.956163786Z     await self.app(scope, receive, _send)
2024-02-22T23:26:20.956167332Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-02-22T23:26:20.956171036Z     raise exc
2024-02-22T23:26:20.956174386Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-02-22T23:26:20.956178116Z     await self.app(scope, receive, sender)
2024-02-22T23:26:20.956181662Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024-02-22T23:26:20.956185423Z     await route.handle(scope, receive, send)
2024-02-22T23:26:20.956188857Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024-02-22T23:26:20.956192501Z     await self.app(scope, receive, send)
2024-02-22T23:26:20.956196227Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024-02-22T23:26:20.956199862Z     response = await func(request)
2024-02-22T23:26:20.956203217Z                ^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956206601Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
2024-02-22T23:26:20.956210333Z     raise e
2024-02-22T23:26:20.956213638Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
2024-02-22T23:26:20.956217258Z     raw_response = await run_endpoint_function(
2024-02-22T23:26:20.956222361Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956226240Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-02-22T23:26:20.956230040Z     return await dependant.call(**values)
2024-02-22T23:26:20.956233464Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956236881Z   File "/backend/api/onboarding/release.py", line 143, in get_release_info
2024-02-22T23:26:20.956240962Z     return ReleaseInfoModel(**res.json())
2024-02-22T23:26:20.956246502Z                               ^^^^^^^^^^
2024-02-22T23:26:20.956251883Z   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 762, in json
2024-02-22T23:26:20.956262589Z     return jsonlib.loads(self.content, **kwargs)
2024-02-22T23:26:20.956268769Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956274192Z   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2024-02-22T23:26:20.956279427Z     return _default_decoder.decode(s)
2024-02-22T23:26:20.956283606Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956288110Z   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2024-02-22T23:26:20.956293093Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-02-22T23:26:20.956298468Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T23:26:20.956303586Z   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2024-02-22T23:26:20.956309238Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-02-22T23:26:20.956314605Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This happens when I click confirm after chosing `ayon_ocio`, `deadline`, `houdini`, `nuke`, `maya`, `traypublisher` from the addons.

**Comment by beatreichenbach** [comment]
Pressing confirm triggers this request:

`GET http://localhost:5000/api/onboarding/releases/2024.01.0-full`

**Comment by martastain** [comment]
Thanks for reporting this. There was an issue with the marketplace, but it should work now.
